# Generated by Django 6.1 on 2026-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_category_alter_contact_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Exibir'),
        ),
    ]
